# Generated by Django 4.0.4 on 2022-06-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
