# Generated by Django 4.0.4 on 2022-06-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_create_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='user',
        ),
        migrations.AlterField(
            model_name='create',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
