# Generated by Django 4.0.4 on 2022-06-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Otro')]),
        ),
    ]
